name: openwmail
version: 1.0.0
summary: WMail
description: WMail
confinement: strict
grade: stable
icon: snap/gui/app.png
apps:
  wmail:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/WMail
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    source: WMail-linux-x64
    after:
      - desktop-glib-only
